export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_CREDENTIAL: 'INVALID_CREDENTIAL',
  REQUIRED_FIELD: 'REQUIRED_FIELD',
  INVALID_JWT: 'INVALID_JWT',
  UNAUTHORIZED: 'UNAUTHORIZED',
  DUPLICATE: 'DUPLICATE',
  SERVER_ERROR: 'SERVER_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  NO_FIELDS_PROVIDED: 'NO_FIELDS_PROVIDED',
  RESOURCE_IN_USED: 'RESOURCE_IN_USED',
  FORBIDDEN: 'FORBIDDEN',
  RESOURCE_ALREADY_REMOVED: 'RESOURCE_ALREADY_REMOVED',
  ALREADY_COMPLETED: 'ALREADY_COMPLETED',
  UPLOAD_IMAGE: 'UPLOAD_IMAGE',
  PASSWORD_SAME_AS_OLD: 'PASSWORD_SAME_AS_OLD',
};

export const DAY_MAP = {
  sunday: 0,
  monday: 1,
  tuesday: 2,
  wednesday: 3,
  thursday: 4,
  friday: 5,
  saturday: 6,
};
